Repository redwoodjs/example-store-stripe, pull requests merged in 2022-02, with the labels that each got.

#24 Use RWJS_API_URL
  web/src/pages/StripeCartPage/StripeCartPage.js
Labels: enhancement

#41 Feat/checkout graphql integration #16
  api/src/graphql/checkouts.sdl.js
  api/src/graphql/stripePrice.sdl.js
  api/src/graphql/stripeProduct.sdl.js
  api/src/services/checkouts/checkouts.js
  api/src/services/stripePrice/stripePrice.js
  web/src/components/Cart/Cart.js
  web/src/components/CartDropDown/CartDropDown.js
  web/src/components/CartDropDownItem/CartDropDownItem.js
  web/src/components/List/List.js
  web/src/components/PriceItem/PriceItem.js
  web/src/components/PricesCell/PricesCell.js
  web/src/components/PricesCell/PricesCell.mock.js
  web/src/components/PricesCell/PricesCell.stories.js
  web/src/components/PricesCell/PricesCell.test.js
  web/src/hooks/useCheckout.js
  web/src/index.css
  web/src/layouts/PublicLayout/PublicLayout.js
  web/src/pages/HomePage/HomePage.js
Labels: feature

#47 Setup Netlify deploy
  .github/workflows/ci.yml
  api/db/schema.prisma
  api/src/services/checkouts/checkouts.js
  netlify.toml
  redwood.toml
Labels: feature

#49 UI-first refactor
  api/package.json
  api/src/functions/checkouts/checkouts.js
  api/src/functions/createCheckoutSession/createCheckoutSession.scenarios.js
  api/src/functions/createCheckoutSession/createCheckoutSession.test.js
  api/src/functions/graphql.js
  api/src/functions/retrieveCheckoutSession/retrieveCheckoutSession.scenarios.js
  api/src/functions/retrieveCheckoutSession/retrieveCheckoutSession.test.js
  api/src/functions/sessions/sessions.js
  api/src/graphql/.keep
  api/src/graphql/checkouts.sdl.js
  api/src/graphql/products.sdl.js
  api/src/graphql/stripePrice.sdl.js
  api/src/graphql/stripeProduct.sdl.js
  api/src/services/.keep
  api/src/services/checkouts/checkouts.js
  api/src/services/checkouts/checkouts.test.js
  api/src/services/products/products.js
  api/src/services/stripePrice/stripePrice.js
  web/package.json
  web/src/App.js
  web/src/Routes.js
  web/src/components/.keep
  web/src/components/Cart/Cart.js
  web/src/components/CartDropDown/CartDropDown.js
  web/src/components/CartDropDownItem/CartDropDownItem.js
  web/src/components/CartProvider/CartProvider.js
  web/src/components/CartProvider/CartProvider.stories.js
  web/src/components/CartProvider/CartProvider.test.js
  web/src/components/GlobalStyles/GlobalStyles.js
  web/src/components/List/List.js
  web/src/components/Logo/Logo.js
  web/src/components/Logo/Logo.stories.js
  web/src/components/Logo/Logo.test.js
  web/src/components/PriceItem/PriceItem.js
  web/src/components/PricesCell/PricesCell.js
  web/src/components/PricesCell/PricesCell.mock.js
  web/src/components/PricesCell/PricesCell.stories.js
  web/src/components/Product/Product.js
  web/src/components/ProductsCell/ProductsCell.js
  web/src/components/ProductsCell/ProductsCell.mock.js
  web/src/components/ProductsCell/ProductsCell.stories.js
  web/src/components/ProductsCell/ProductsCell.test.js
  web/src/components/SiteWrapper/SiteWrapper.js
  web/src/hooks/useCheckout.js
  web/src/index.css
  web/src/layouts/.keep
  web/src/layouts/MainLayout/MainLayout.js
  web/src/layouts/MainLayout/MainLayout.stories.js
  web/src/layouts/MainLayout/MainLayout.test.js
  web/src/layouts/PublicLayout/PublicLayout.js
  web/src/layouts/PublicLayout/PublicLayout.stories.js
  web/src/layouts/PublicLayout/PublicLayout.test.js
  web/src/pages/HomePage/HomePage.js
  web/src/pages/StripeCartPage/StripeCartPage.js
  web/src/pages/StripeCartPage/StripeCartPage.stories.js
  yarn.lock
Labels: enhancement

#55 Fix/duplicate products
  api/src/graphql/products.sdl.js
  api/src/services/products/products.js
  web/src/components/Product/Product.js
  web/src/components/ProductsCell/ProductsCell.js
  web/src/pages/HomePage/HomePage.js
Labels: bug
